spring:
  datasource:
    url: jdbc:sqlserver://sql-nutrifom.database.windows.net:1433;database=sqldb-nutrifom;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: nutriadmin
    password: S%a^VNLHDnZTw^00
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8080