name: Deploy React App to Azure App Service

on:
  push:
    branches:
      - main  # Setzen Sie hier Ihren Hauptbranch ein

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'

    - name: Build React App
      run: |
        cd nutrifom-ui
        npm install
        npm run build

    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'IhrAppServiceName' # Setzen Sie hier den Namen Ihres Azure App Service ein
        slot-name: 'production' # Optional: Wenn Sie einen bestimmten Slot verwenden
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Setzen Sie Ihr Azure Publish-Profil als Geheimnis in den GitHub Secrets
        package: nutrifom-ui/build
