name: Build and deploy Java app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: |
          cd nutrifom-api
          ./mvnw package -DskipTests # Hier könnten Sie Ihre Tests laufen lassen, wenn gewünscht

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: spring-boot-api
          path: nutrifom-api/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: spring-boot-api

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Name Ihres Azure App Service'
          slot-name: 'production' # Optional, wenn Sie Deployment Slots verwenden
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
